# version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    container_name: postgres_PB_DESAFIO
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
volumes:
  db_data: